- name: Create /root/bin directory
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: 0770


- name: Copy scripts (root)
  copy:
    src: "{{ item }}"
    dest: /root/bin/
    owner: root
    group: root
    mode: 0770
  with_fileglob:
    - root/bin/*


- block:
  - name: Create /home/{{ sudo_user }}/bin
    file:
      path: "/home/{{ sudo_user }}/bin"
      state: directory
      owner: "{{ sudo_user }}"
      group: "{{ sudo_user }}"
      mode: 0770

  - name: Copy scripts ({{ sudo_user }})
    copy:
      src: "{{ item }}"
      dest: "/home/{{ sudo_user }}/bin/"
      owner: "{{ sudo_user }}"
      group: "{{ sudo_user }}"
      mode: 0770
    with_fileglob:
      - sudo_user/bin/*
  when: sudo_user is defined
